#name: CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      
      - name: Download Scantist-Bom-Detect
        run: curl -s https://scripts.scantist.com/scantist-bom-detect.jar --output scantist-bom-detect.jar
      
      - name: Upload to Scantist 
        env: # Setting the Token
          SCANTISTTOKEN: ${{secrets.SCANTISTTOKEN}}
          SCANTIST_IMPORT_URL : "https://api-staging.scantist.io/ci-scan/" 
        run: java -jar scantist-bom-detect.jar
